disabled_rules:
- trailing_whitespace
- line_length
- identifier_name
- type_name
  
opt_in_rules:
- empty_count
- empty_string
- sorted_imports
- trailing_closure
- vertical_whitespace_between_cases
- yoda_condition

included:

excluded:
- /Tuist
- '**/Project.swift'
- '**/Derived/**'

custom_rules:
  no_print_statements:
    name: "나야 프린트..."
    regex: "print\\s*\\(.*\\)"
    message: "You should remove print statements."
    severity: warning